services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
  db:
    image: arm64v8/mongo:5.0.17
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: nest

volumes:
  mongodb_data:
    driver: local
